version: "3"

services:
  db:
    container_name: mysql-db
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_DATABASE=yousinsa
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./db:/var/lib/mysql # db 볼륨 처리
    ports:
      - 8738:3306  

  app:
    container_name: yousinsa-app
    image: rlfbd5142/yousinsa:latest
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    restart: always

  staging-app:
    container_name: yousinsa-staging-app
    image: rlfbd5142/yousinsa-staging:latest
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./staging-app:/app
    working_dir: /app
    restart: always

  staging-db:
    container_name: mysql-staging-db
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_DATABASE=yousinsa
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./staging-db:/var/lib/mysql # db 볼륨 처리
    ports:
      - 8740:3306
