version: "3"

services:
  app:
    container_name: yousinsa-app
    image: rlfbd5142/yousinsa:latest
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
    working_dir: /app
    restart: always


